Primeira versao React
JohnnyRezender/reminder-project pull request #7
Opened 2020-09-10 17:30 UTC by Ramos03

Primeira versão do react com as telas.

-> SPA incluído.

2020-09-15 23:37 UTC, JohnnyRezender requested changes

2020-09-15 23:37 UTC, JohnnyRezender commented on web/debug.log
> +[0909/131014.614:ERROR:crash_report_database_win.cc(469)] failed to stat report
Remover logs desnecessários.

2020-09-15 23:37 UTC, JohnnyRezender commented on web/public/debug.log
> +[0909/141219.091:ERROR:crash_report_database_win.cc(469)] failed to stat report
Remover logs desnecessários.
Se esse arquivo for criado automáticamente, seria interessante deixar no .gitignore, não?

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/components/ReminderList/index.tsx
> +function ReminderItem() {
Inserir requisição para backend buscando os lembretes e colocar tratativa de erro para caso a requisição falhar ou nenhum lembrete ser retornado.

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +        const data = {
Alterar para:
```
        const data = {
            ST_REMINDER_REM: name,
            DT_LEMBRETE_REM: dateReminder
        }
```

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +        const { name, email, nameReminder, reminder, dateReminder } = formData;
Receber apenas o lembrete e sua data

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +    return (
Excluir elementos desnecessários:
- name
- email
- reminder

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +                            <label htmlFor="dateReminder">Data do lembrete</label>
Mudar o formato para data e hora

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/pages/ReminderList/index.tsx
> +            <PageHeader title="Estes são os lembretes cadastrados">
Acho que poderíamos deixar a opção para buscar lembretes por nome ou data para uma próxima versão. E fazer o backend retornar apenas os lembretes que estão pendentes.

2020-09-15 23:37 UTC, JohnnyRezender commented on web/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Para que serve este arquivo?

2020-09-15 23:43 UTC, JohnnyRezender requested changes

2020-09-15 23:43 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +        await api.post('reminders', data);
Será preciso validar o response dessa requisição tbm, pois back-end tem várias travas para cadastro de lembretes

2020-09-15 23:43 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +                            <input
Adicionar `required` no elemento

2020-09-15 23:43 UTC, JohnnyRezender commented on web/src/pages/ReminderForm/index.tsx
> +                            <input
Adicionar `required` no campo de data

2020-09-29 22:55 UTC, JohnnyRezender commented
Approved

2020-10-14 14:07 UTC, Ramos03 commented on web/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Esse arquivo é criado pelo react, para usar ts.

2020-10-14 14:20 UTC, closed without merging