React
JohnnyRezender/reminder-project pull request #8
Opened 2020-10-14 14:22 UTC by Ramos03

Finalizado a primeira versão do front, com react.

Cadastrando e retornando dados.
Feito uma tratativa no cadastro para retornar a mensagem do back.

2020-10-15 01:46 UTC, JohnnyRezender requested changes
Rever considerações e remover o arquivo `server/database/database.sqlite`, por favor.

2020-10-15 01:46 UTC, JohnnyRezender commented on web/debug.log
> +[0909/131014.614:ERROR:crash_report_database_win.cc(469)] failed to stat report
Mano, não vejo sentido em subir esse arquivo no Git. Pode deletar ele .

2020-10-15 01:46 UTC, JohnnyRezender commented on web/public/debug.log
> +[0909/141219.091:ERROR:crash_report_database_win.cc(469)] failed to stat report
Acredito que esse arquivo pode ser removido dessa branch também.

2020-10-15 01:46 UTC, JohnnyRezender commented on server/controllers/RemindersController.ts
> +        console.log("OI");
Remover console.log

2020-10-15 01:46 UTC, JohnnyRezender commented on server/package.json
> +    "nodemon": "^2.0.4",
O nodemon é uma ferramenta que não atualiza a aplicação sem precisar parar a aplicação e iniciar novamente correto? Se a utilização dele for por esse motivo, não há a necessidade em utiliza-lo. Pois atualmente a aplicação já é reiniciada.

2020-10-15 01:46 UTC, JohnnyRezender commented on web/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Qual o motivo de upar esse arquivo vazio?

2020-10-15 01:46 UTC, JohnnyRezender commented on web/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
O Readme poderia mostrar alguns prints das telas

2020-10-15 01:46 UTC, JohnnyRezender commented on web/src/components/ReminderList/index.tsx
> +            getReminders(response.data);
Como funciona esse componente? ví que a função `getReminders` está comentada.

2020-10-16 12:38 UTC, Ramos03 commented on web/src/components/ReminderList/index.tsx
> +            getReminders(response.data);
Desconsidera, a função correta estava abaixo

2020-10-16 12:47 UTC, closed without merging